theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons1: "formatselect,bold,italic,underline,sub,sup,separator,bullist,numlist,separator,link,pastetext,pasteword,separator,forecolor,backcolor,separator,code"
theme_advanced_buttons2: ""
theme_advanced_buttons3: ""
# theme_advanced_buttons3_add:
#   - tablecontrols
#   - fullscreen
plugins:
  - advlink
  - paste
  - style
#  - table
#   - fullscreen
theme: advanced
force_br_newlines: true
force_p_newlines: false
forced_root_block: ''