
# theme_advanced_buttons3_add:
#   - tablecontrols
#   - fullscreen
plugins: "link paste"
paste_as_text: true
menubar: true
#  - table
#   - fullscreen
theme: modern
force_br_newlines: true
force_p_newlines: false
forced_root_block: ''
content_css: '/assets/tiny_content.css'